// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using OnlineShopAdmin.DataAccess.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OnlineShopAdmin.DataAccess.Models
{
    /// <summary>
    /// Street address information for customers.
    /// </summary>
    public partial class Address : BaseProperTy
    {
        public Address()
        {
            CustomerAddresses = new HashSet<CustomerAddress>();
            SalesOrderHeaderBillToAddresses = new HashSet<SalesOrderHeader>();
            SalesOrderHeaderShipToAddresses = new HashSet<SalesOrderHeader>();
        }

        /// <summary>
        /// Primary key for Address records.
        /// </summary>
        public int AddressId { get; set; }
        /// <summary>
        /// First street address line.
        /// </summary>
        [Required(ErrorMessage = "Mandatory Field!")]
        [MaxLength(60, ErrorMessage = "Maximum 60 Characters!")]
        public string AddressLine1 { get; set; }
        /// <summary>
        /// Second street address line.
        /// </summary>
        [MaxLength(60, ErrorMessage = "Maximum 60 Characters!")]
        public string AddressLine2 { get; set; }
        /// <summary>
        /// Name of the city.
        /// </summary>
        [Required(ErrorMessage = "Mandatory Field!")]
        [MaxLength(30, ErrorMessage = "Maximum 30 Characters!")]
        public string City { get; set; }
        /// <summary>
        /// Name of state or province.
        /// </summary>
        [Required(ErrorMessage = "Mandatory Field!")]
        [MaxLength(50, ErrorMessage = "Maximum 50 Characters!")]
        public string StateProvince { get; set; }
        
        [Required(ErrorMessage = "Mandatory Field!")]
        [MaxLength(50, ErrorMessage = "Maximum 50 Characters!")]
        public string CountryRegion { get; set; }
        /// <summary>
        /// Postal code for the street address.
        /// </summary>
        [Required(ErrorMessage = "Mandatory Field!")]
        [MaxLength(15, ErrorMessage = "Maximum 15 Characters!")]
        public string PostalCode { get; set; }
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public Guid Rowguid { get; set; }
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        

        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
        public virtual ICollection<SalesOrderHeader> SalesOrderHeaderBillToAddresses { get; set; }
        public virtual ICollection<SalesOrderHeader> SalesOrderHeaderShipToAddresses { get; set; }
    }
}