// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Http;
using OnlineShopAdmin.DataAccess.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OnlineShopAdmin.DataAccess.Models
{
    /// <summary>
    /// Products sold or used in the manfacturing of sold products.
    /// </summary>
    public partial class Product : BaseProperTy
    {
        public Product()
        {
            SalesOrderDetails = new HashSet<SalesOrderDetail>();
        }

        /// <summary>
        /// Primary key for Product records.
        /// </summary>
        public int ProductId { get; set; }
        /// <summary>
        /// Name of the product.
        /// </summary>
        [Required(ErrorMessage = "Mandatory Field!")]
        [MaxLength(50, ErrorMessage = "Maximum 50 Characters!")]
        public string Name { get; set; }
        /// <summary>
        /// Unique product identification number.
        /// </summary>
        [Required(ErrorMessage = "Mandatory Field!")]
        [MaxLength(25, ErrorMessage = "Maximum 25 Characters!")]
        public string ProductNumber { get; set; }
        /// <summary>
        /// Product color.
        /// </summary>
        [MaxLength(15, ErrorMessage = "Maximum 15 Characters!")]
        public string Color { get; set; }
        /// <summary>
        /// Standard cost of the product.
        /// </summary>
        [Required(ErrorMessage = "Mandatory Field!")]
        //[DisplayFormat(DataFormatString = "{0:0.0000}")]
        public decimal? StandardCost { get; set; }
        /// <summary>
        /// Selling price.
        /// </summary>
        [Required(ErrorMessage = "Mandatory Field!")]
        //[DisplayFormat(DataFormatString = "{0:0.0000}")]
        public decimal? ListPrice { get; set; }
        /// <summary>
        /// Product size.
        /// </summary>
        [MaxLength(5, ErrorMessage = "Maximum 5 Characters!")]
        public string Size { get; set; }
        /// <summary>
        /// Product weight.
        /// </summary>
        public decimal? Weight { get; set; }
        /// <summary>
        /// Product is a member of this product category. Foreign key to ProductCategory.ProductCategoryID. 
        /// </summary>
        public int? ProductCategoryId { get; set; }
        /// <summary>
        /// Product is a member of this product model. Foreign key to ProductModel.ProductModelID.
        /// </summary>
        public int? ProductModelId { get; set; }
        /// <summary>
        /// Date the product was available for sale.
        /// </summary>
        [Required(ErrorMessage = "Mandatory Field!")]
        public DateTime? SellStartDate { get; set; }
        /// <summary>
        /// Date the product was no longer available for sale.
        /// </summary>
        public DateTime? SellEndDate { get; set; }
        /// <summary>
        /// Date the product was discontinued.
        /// </summary>
        public DateTime? DiscontinuedDate { get; set; }
        /// <summary>
        /// Small image of the product.
        /// </summary>
        public byte[] ThumbNailPhoto { get; set; }
        /// <summary>
        /// Small image file name.
        /// </summary>
        public string ThumbnailPhotoFileName { get; set; }
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public Guid Rowguid { get; set; }
        [NotMapped]
        //[Required(ErrorMessage = "Please choose profile image")]
      
        public IFormFile Photo { get; set; }

        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductModel ProductModel { get; set; }
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }
    }
}